from .input_specs import InputSpecsPage
from .pre_design import PreDesignPage
from .transformer import TransformerPage
from .transformer_recap import TransformerRecapPage
from .wire_sections import WireSectionsPage
from .snubber import SnubberPage
from .losses import LossesPage
from .output_stage import OutputStagePage
from .structure import StructurePage